# Base image with Node.js
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Set environment variables
ENV NODE_ENV development

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
